# Site wide configuration

title: CodeMyntra Blog | India
locale: en_US
description:  Blog on Engineering, Ruby on Rails, Nodejs, Angularjs, Reactjs, JavaScript and Ecosystem around Development, Culture and many more... | CodeMyntra
logo: site-logo.png
search: true
url: http://blog.codemyntra.com

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: CodeMyntra
  avatar: bio-photo.jpg
  email: contact@codemyntra.com
  disqus-shortname: blog-codemyntra-com
  twitter: codemyntra
  facebook: codemyntra
  github: codemyntra
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: codemyntra
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client: UA-97609234-1
    ad-slot:
  bing-verify:
